#!/bin/bash
# Author: Gutierrez Adrian
# Last Updated: 23 Nov 2020
# Purpose: This bash script allows users to add servers
# to a text file and then allows users to choose to ssh
# or sftp to a server on the list in the text file.
#

SERVER_LIST="/var/tmp/serverNames.txt"
SPLASHSCREEN="/var/tmp/main.txt"

add_domain_names() {
    echo "Ok, let's add a domain name..."
    read -rp "Enter domain name: " name
    echo "$name" >> $SERVER_LIST
    echo "Ok, "$name" server added to list!"
}

quit_program() {
    echo "Ok, goodbye $USER!"
    exit 1
}

ssh_server() {
    echo "OK, let's SSH..."
    read -p "Username: " username
    echo "Here are the list of servers:"
    echo "#############################################################################"
    cat $SERVER_LIST
    echo "#############################################################################"
    read -p "Choose server: " line
    servername=$(head -n $line $SERVER_LIST | tail -1)
    ssh "$username@$servername"
}

sftp_server() {
    echo "OK, let's SFTP..."
    read -p "Username: " username
    echo "Here are the list of servers:"
    echo "#############################################################################"
    cat $SERVER_LIST
    echo "#############################################################################"
    read -p "Choose server: " line
    servername=$(head -n $line $SERVER_LIST | tail -1)
    sftp "$username@$servername"
}

loading() {
    echo -ne '#####                     (33%)\r'
    sleep 1
    echo -ne '#############             (66%)\r'
    sleep 1
    echo -ne '#######################   (100%)\r'
    echo -ne '\n'
}

main_menu() {
    PS3='Please enter your choice: '
    options=("SSH" "SFTP" "Add Domain" "Quit")
    select opt in "${options[@]}"
    do
        case $opt in
            "SSH")
                ssh_server
                break
                ;;
            "SFTP")
                sftp_server
                break
                ;;
            "Add Domains")
                add_domain_names
                break
                ;;
            "Quit")
                quit_program
                break
                ;;
            *) echo "Invalid Option $REPLY";;
        esac
    done
}

get_info() {
    echo -e "-------------------------------System Information----------------------------"
    echo -e "Hostname:\t\t"`hostname`
    echo -e "uptime:\t\t\t"`uptime | awk '{print $3,$4}' | sed 's/,//'`
    echo -e "Operating System:\t"`hostnamectl | grep "Operating System" | cut -d ' ' -f5-`
    echo -e "Kernel:\t\t\t"`uname -r`
    echo -e "Architecture:\t\t"`arch`
    echo -e "Processor Name:\t\t"`awk -F':' '/^model name/ {print $2}' /proc/cpuinfo | uniq | sed -e 's/^[ \t]*//'`
    echo -e "Active User:\t\t"`w | cut -d ' ' -f1 | grep -v USER | xargs -n1`
    echo ""
    echo -e "-------------------------------CPU/Memory Usage------------------------------"
    echo -e "Memory Usage:\t"`free | awk '/Mem/{printf("%.2f%"), $3/$2*100}'`
    echo -e "Swap Usage:\t"`free | awk '/Swap/{printf("%.2f%"), $3/$2*100}'`
    echo -e "CPU Usage:\t"`cat /proc/stat | awk '/cpu/{printf("%.2f%\n"), ($2+$4)*100/($2+$4+$5)}' |  awk '{print $0}' | head -1`
    echo ""
    #echo -e "-------------------------------Package Updates-------------------------------"
    # sudo cat /var/lib/update-notifier/updates-available
    echo -e "-----------------------------------------------------------------------------"
}

main() {
    echo "Hello $USER, what would you like to do today?"
    sleep 1
    while true; do
        main_menu
    done
}

if [ ! -f "$SERVER_LIST" ] || [ ! -f $SPLASHSCREEN ]; then
    echo "FILES DO NOT EXIST...\n"
    sleep 2
    echo "CREATING NECESSARY FILES...\n"
    loading
    touch $SERVER_LIST
    touch $SPLASHSCREEN
    echo "
#############################################################################
          _____                    _____            _____                  
         /\    \                  /\    \          /\    \                 
        /::\    \                /::\____\        /::\    \                
       /::::\    \              /:::/    /       /::::\    \               
      /::::::\    \            /:::/    /       /::::::\    \              
     /:::/\:::\    \          /:::/    /       /:::/\:::\    \             
    /:::/__\:::\    \        /:::/    /       /:::/__\:::\    \            
    \:::\   \:::\    \      /:::/    /        \:::\   \:::\    \           
  ___\:::\   \:::\    \    /:::/    /       ___\:::\   \:::\    \          
 /\   \:::\   \:::\    \  /:::/    /       /\   \:::\   \:::\    \         
/::\   \:::\   \:::\____\/:::/____/       /::\   \:::\   \:::\____\        
\:::\   \:::\   \::/    /\:::\    \       \:::\   \:::\   \::/    /        
 \:::\   \:::\   \/____/  \:::\    \       \:::\   \:::\   \/____/         
  \:::\   \:::\    \       \:::\    \       \:::\   \:::\    \             
   \:::\   \:::\____\       \:::\    \       \:::\   \:::\____\            
    \:::\  /:::/    /        \:::\    \       \:::\  /:::/    /            
     \:::\/:::/    /          \:::\    \       \:::\/:::/    /             
      \::::::/    /            \:::\    \       \::::::/    /              
       \::::/    /              \:::\____\       \::::/    /               
        \::/    /                \::/    /        \::/    /                
         \/____/                  \/____/          \/____/                 
                                                                           
#############################################################################
Welcome to the Server Login System              ----------------------v.2.1.1
Created by: Adrian Gutierrez
Licensed under GNU General Public License v3

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#" >> $SPLASHSCREEN
$0 

else
    cat $SPLASHSCREEN
    echo "Getting system info...\n"
    sleep 1
    loading
    get_info
    main
fi
